### PR TITLE
Use font-awesome icons

### PR DESCRIPTION
**Pull request by chris-rudmin**
Fix alignment of close x.
Fix small arrow icons in firefox on retina screen.
screen shot 2015-08-21 at 4 01 08 pm
screen shot 2015-08-21 at 4 01 19 pm
screen shot 2015-08-21 at 4 00 14 pm

### CODE REVIEW

**Comment by spasiu** [comment]
:+1:

**Comment by chris-rudmin** [comment]
@kvgauthier @lemieux @juliangarritano

**Comment by lemieux** [comment]
@chris-rudmin  was this tested on Windows and Linux too?

**Comment by chris-rudmin** [comment]
@lemieux I tested windows in a VM, but not linux.  Can you check it out for me?

**Comment by lemieux** [comment]
Yep won't be long

**Comment by lemieux** [comment]
all good :+1:

**Pull request merged**
