### PR TITLE
Removed package.json deps to Bootstrap and Font-Awesome

### LINKED ISSUE #79: FontAwesome dependency not downloading with npm
After doing `npm install`on a 0.2.24 version all dependencies download except for font awesome. Which causes build problems.

```
supportkit@0.2.24 node_modules/supportkit
├── cookie@0.1.3
├── url-join@0.0.1
├── view-controller@1.0.4
├── marionette.behaviors@0.0.13
├── uuid@2.0.1
├── underscore@1.8.3
├── backbone@1.2.1
├── backbone.stickit@0.9.2
├── backbone-computedfields@0.0.10 (underscore@1.5.2, backbone@1.1.2)
├── jquery@1.11.3
├── bootstrap@3.3.5
├── backbone-associations@0.6.2
├── urljoin@0.1.5 (extend@2.0.1)
├── backbone.marionette@2.4.2 (backbone.babysitter@0.1.8, backbone.wreqr@1.3.3)
├── lodash.bindall@3.1.0 (lodash.restparam@3.6.1, lodash._baseflatten@3.1.4, lodash._createwrapper@3.0.7, lodash.functions@3.0.0)
├── faye@1.1.2 (tunnel-agent@0.4.1, tough-cookie@2.0.0, csprng@0.1.1, faye-websocket@0.10.0)
├── jstify@0.7.0 (through2@0.6.5, html-minifier@0.6.9)
└── node-lessify@0.0.10 (object-assign@2.1.1, through2@0.6.5, less@2.4.0)```

### PR DESCRIPTION
**Pull request by lemieux**
I copied the files we needed in the project instead. This will fix #79 .

### CODE REVIEW

**Comment by jpjoyal** [comment]
This looks like a lot of css to bundle into our need-a-diet bundle. Are we sure this won't clash with bootstrap & font-awesome ?

**Comment by jpjoyal** [comment]
What about stripping down the stuff we don't use ?

**Comment by lemieux** [comment]
It's the same as before, most of these files are mixins that are not in the built

**Comment by lemieux** [comment]
And it should not class with font-awesome since everything is scoped under #sk-container. Our style should prevail unless elements are targetted with #sk-container #sk-wrapper in the application stylesheets which means our widget will look the same everywhere unless styled by the developer.

**Comment by mspensieri** [comment]
:+1:

**Comment by jpjoyal** [comment]
:shipit:

**Comment by dannytranlx** [comment]
:+1:

**Pull request merged**
